# Solution to NumPy exercises

---

In [1]:
import numpy as np

## 1.12 EXERCISES Creating array

<div class="alert alert-success">

<b>EXERCISES</b>:

 <ul>
  <li>Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10</li>
</ul>
 <ul>
  <li>Write a NumPy program to create a array with values ranging from 12 to 38</li>
</ul>
<ul>
  <li>Write a NumPy program to create a 2-dimensional array of size 2 x 3 (composed of 4-byte integer elements), also print the shape, type and data type of the array.</li>
</ul>
</div>

https://www.w3resource.com/python-exercises/numpy/python-numpy-exercise-3.php   
https://www.w3resource.com/python-exercises/numpy/python-numpy-exercise-5.php   
https://www.w3resource.com/python-exercises/numpy/python-numpy-exercise-37.php  


In [2]:
x =  np.arange(2, 11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [3]:
x = np.arange(12, 38)
print(x)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [4]:
x = np.array([[2, 4, 6], [6, 8, 10]], np.int32)
print(type(x))	
print(x.shape)
print(x.dtype)

<class 'numpy.ndarray'>
(2, 3)
int32


## 2.4 EXERCISES Reshaping an array

<div class="alert alert-success">

<b>EXERCISE</b>:

<ul>
  <li>Write a NumPy program to change the dimension of an array: 6 rows and 0 columns = (6,) -> 
(3, 3) = 3 rows and 3 columns</li>
</ul>

https://www.w3resource.com/python-exercises/numpy/python-numpy-exercise-35.php

In [5]:
x = np.array([1, 2, 3, 4, 5, 6])
print("6 rows and 0 columns")
print(x.shape)

y = np.array([[1, 2, 3],[4, 5, 6],[7,8,9]])
print("(3, 3) -> 3 rows and 3 columns ")
print(y)

x = np.array([1,2,3,4,5,6,7,8,9])
print("Change array shape to (3, 3) -> 3 rows and 3 columns ")
x.shape = (3, 3)
print(x)


6 rows and 0 columns
(6,)
(3, 3) -> 3 rows and 3 columns 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Change array shape to (3, 3) -> 3 rows and 3 columns 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## 4.5 EXERCISES Broadcasting

<div class="alert alert-success">

<b>EXERCISES</b>:

<ul>
  <li>Write a NumPy program to broadcast on different shapes of arrays where p(3,3) + q(3).</li>
</ul>
<ul>
  <li>Write a NumPy program to broadcast on different shapes of arrays where a(,3) + b(3).</li>
</ul>

https://www.w3resource.com/python-exercises/numpy/python-numpy-exercise-124.php  
https://www.w3resource.com/python-exercises/numpy/python-numpy-exercise-125.php

In [6]:
p = np.array([[0, 0, 0],
              [1, 2, 3],
              [4, 5, 6]]) 
q= np.array([10, 11, 12]) 
print("Original arrays:")
print("Array-1")
print(p)
print("Array-2")
print(q)
print("\nNew Array:")
new_array1 = p + q 
print(new_array1)

Original arrays:
Array-1
[[0 0 0]
 [1 2 3]
 [4 5 6]]
Array-2
[10 11 12]

New Array:
[[10 11 12]
 [11 13 15]
 [14 16 18]]


In [7]:
p = np.array([[0], [10], [20]]) 
q= np.array([10, 11, 12]) 
print("Original arrays:")
print("Array-1")
print(p)
print("Array-2")
print(q)
print("\nNew Array:")
new_array1 = p + q 
print(new_array1)

Original arrays:
Array-1
[[ 0]
 [10]
 [20]]
Array-2
[10 11 12]

New Array:
[[10 11 12]
 [20 21 22]
 [30 31 32]]


## 6.4 EXERCISES Mathematical and statistical functions

<div class="alert alert-success">

<b>EXERCISES</b>:

<ul>
  <li>Write a NumPy program to compute logarithm of the sum of exponentiations of the inputs, sum of exponentiations of the inputs in base-2.</li>
</ul>
<ul>
  <li>Write a NumPy program to get true division of the element-wise array inputs.</li>
</ul>
<ul>
  <li>Write a NumPy program to multiply a matrix by another matrix of complex numbers and create a new matrix of complex numbers.</li>
</ul>
<ul>
  <li>Write a NumPy program to calculate round, floor, ceiling, truncated and round (to the given number of decimals) of the input, element-wise of a given array. </li>
</ul>


https://www.w3resource.com/python-exercises/numpy/python-numpy-math-exercise-2.php  
https://www.w3resource.com/python-exercises/numpy/python-numpy-math-exercise-3.php  
https://www.w3resource.com/python-exercises/numpy/python-numpy-math-exercise-12.php  
https://www.w3resource.com/python-exercises/numpy/python-numpy-math-exercise-26.php  

In [8]:
l1 = np.log(1e-50)
l2 = np.log(2.5e-50)
print("Logarithm of the sum of exponentiations:")
print(np.logaddexp(l1, l2))
print("Logarithm of the sum of exponentiations of the inputs in base-2:")
print(np.logaddexp2(l1, l2))



Logarithm of the sum of exponentiations:
-113.87649168120691
Logarithm of the sum of exponentiations of the inputs in base-2:
-113.59955522772194


In [9]:
x = np.arange(10)
print("Original array:")
print(x)
print("Division of the array inputs, element-wise:")
print(np.true_divide(x, 3))


Original array:
[0 1 2 3 4 5 6 7 8 9]
Division of the array inputs, element-wise:
[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333 2.66666667 3.        ]


In [10]:
x = np.array([1+2j,3+4j])
print("First array:")
print(x)
y = np.array([5+6j,7+8j])
print("Second array:")
print(y)
z = np.vdot(x, y)
print("Product of above two arrays:")
print(z)

First array:
[1.+2.j 3.+4.j]
Second array:
[5.+6.j 7.+8.j]
Product of above two arrays:
(70-8j)


In [11]:
x = np.array([3.1, 3.5, 4.5, 2.9, -3.1, -3.5, -5.9])
print("Original array: ")
print(x)
r1 = np.around(x)
r2 = np.floor(x)
r3 = np.ceil(x)
r4 = np.trunc(x)
r5 = [round(elem) for elem in x]

print("\naround:   ", r1)
print("floor:    ",r2)
print("ceil:     ",r3)
print("trunc:    ",r4)
print("round:    ",r5)

Original array: 
[ 3.1  3.5  4.5  2.9 -3.1 -3.5 -5.9]

around:    [ 3.  4.  4.  3. -3. -4. -6.]
floor:     [ 3.  3.  4.  2. -4. -4. -6.]
ceil:      [ 4.  4.  5.  3. -3. -3. -5.]
trunc:     [ 3.  3.  4.  2. -3. -3. -5.]
round:     [3.0, 4.0, 4.0, 3.0, -3.0, -4.0, -6.0]


## 7.7 EXERCISES Array indexing

<div class="alert alert-success">

<b>EXERCISES</b>:

<ul>
  <li>Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort the array on height.</li>
</ul>
<ul>
  <li>Write a NumPy program to sort the student id with increasing height of the students from given students id and height. Print the integer indices that describes the sort order by multiple columns and the sorted data.</li>
</ul>

https://www.w3resource.com/python-exercises/numpy/python-numpy-sorting-and-searching-exercise-2.php
https://www.w3resource.com/python-exercises/numpy/python-numpy-sorting-and-searching-exercise-4.php

In [12]:
data_type = [('name', 'S15'), ('class', int), ('height', float)]
students_details = [('James', 5, 48.5), ('Nail', 6, 52.5),('Paul', 5, 42.10), ('Pit', 5, 40.11)]
# create a structured array
students = np.array(students_details, dtype=data_type)   
print("Original array:")
print(students)
print("Sort by height")
print(np.sort(students, order='height')) 


Original array:
[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 )
 (b'Pit', 5, 40.11)]
Sort by height
[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
 (b'Nail', 6, 52.5 )]


In [13]:
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
student_height = np.array([40., 42., 45., 41., 38., 40., 42.0])
#Sort by studen_id then by student_height
indices = np.lexsort((student_id, student_height))
print("Sorted indices:")
print(indices)
print("Sorted data:")
for n in indices:
  print(student_id[n], student_height[n])

Sorted indices:
[4 0 5 3 6 1 2]
Sorted data:
1682 38.0
1023 40.0
5241 40.0
1671 41.0
4532 42.0
5202 42.0
6230 45.0


## EXERCISES Splitting arrays

<div class="alert alert-success">

<b>EXERCISES</b>:

<ul>
  <li>Write a NumPy program to split an given array into multiple sub-arrays vertically (row-wise). </li>
</ul>
<ul>
  <li>Write a NumPy program to split array into multiple sub-arrays along the 3rd axis.</li>
</ul>

https://www.w3resource.com/python-exercises/numpy/python-numpy-exercise-131.php  
https://www.w3resource.com/python-exercises/numpy/python-numpy-exercise-132.php

In [14]:
print("\nOriginal arrays:")
x = np.arange(16.0).reshape(4, 4)
print(x)
new_array1 =  np.vsplit(x, 2)
print("\nSplit an array into multiple sub-arrays vertically:")
print(new_array1)



Original arrays:
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]

Split an array into multiple sub-arrays vertically:
[array([[0., 1., 2., 3.],
       [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])]


In [15]:

print("\nOriginal arrays:")
x = np.arange(16.0).reshape(2, 2, 4)
print(x)
new_array1 = np.dsplit(x, 2)
print("\nsplit array into multiple sub-arrays along the 3rd axis:")
print(new_array1)


Original arrays:
[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]]

 [[ 8.  9. 10. 11.]
  [12. 13. 14. 15.]]]

split array into multiple sub-arrays along the 3rd axis:
[array([[[ 0.,  1.],
        [ 4.,  5.]],

       [[ 8.,  9.],
        [12., 13.]]]), array([[[ 2.,  3.],
        [ 6.,  7.]],

       [[10., 11.],
        [14., 15.]]])]


## EXERCISES Linear Algebra

<div class="alert alert-success">

<b>EXERCISES</b>:

<ul>
  <li>Write a NumPy program to compute the multiplication of two given matrixes. </li>
</ul>
<ul>
  <li>Write a NumPy program to compute the outer product of two given vectors.</li>
</ul>
<ul>
  <li>Write a NumPy program to compute the eigenvalues and right eigenvectors of a given square array.</li>
</ul>
<ul>
  <li>Write a NumPy program to calculate the QR decomposition of a given matrix.</li>
</ul>
<ul>
  <li>Write a NumPy program to get the qr factorization of a given array.</li>
</ul>


https://www.w3resource.com/python-exercises/numpy/linear-algebra/numpy-linear-algebra-exercise-1.php  
https://www.w3resource.com/python-exercises/numpy/linear-algebra/numpy-linear-algebra-exercise-2.php
https://www.w3resource.com/python-exercises/numpy/linear-algebra/numpy-linear-algebra-exercise-7.php
https://www.w3resource.com/python-exercises/numpy/linear-algebra/numpy-linear-algebra-exercise-13.php
https://www.w3resource.com/python-exercises/numpy/linear-algebra/numpy-linear-algebra-exercise-17.php

In [16]:
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
print("original matrix:")
print(p)
print(q)
result1 = np.dot(p, q)
print("Result of the said matrix multiplication:")
print(result1)

original matrix:
[[1, 0], [0, 1]]
[[1, 2], [3, 4]]
Result of the said matrix multiplication:
[[1 2]
 [3 4]]


In [17]:
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
print("original matrix:")
print(p)
print(q)
result = np.outer(p, q)
print("Outer product of the said two vectors:")
print(result)

original matrix:
[[1, 0], [0, 1]]
[[1, 2], [3, 4]]
Outer product of the said two vectors:
[[1 2 3 4]
 [0 0 0 0]
 [0 0 0 0]
 [1 2 3 4]]


In [18]:
m = np.mat("3 -2;1 0")
print("Original matrix:")
print("a\n", m)
w, v = np.linalg.eig(m) 
print( "Eigenvalues of the said matrix",w)
print( "Eigenvectors of the said matrix",v)

Original matrix:
a
 [[ 3 -2]
 [ 1  0]]
Eigenvalues of the said matrix [2. 1.]
Eigenvectors of the said matrix [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [19]:
m = np.array([[1,2],[3,4]])
print("Original matrix:")
print(m)
result =  np.linalg.qr(m)
print("Decomposition of the said matrix:")
print(result)

Original matrix:
[[1 2]
 [3 4]]
Decomposition of the said matrix:
(array([[-0.31622777, -0.9486833 ],
       [-0.9486833 ,  0.31622777]]), array([[-3.16227766, -4.42718872],
       [ 0.        , -0.63245553]]))


In [20]:
a = np.array([[4, 12, -14], [12, 37, -53], [-14, -53, 98]], dtype=np.int32)
print("Original array:")
print(a)
q, r = np.linalg.qr(a)
print("qr factorization of the said array:")
print( "q=\n", q, "\nr=\n", r)

Original array:
[[  4  12 -14]
 [ 12  37 -53]
 [-14 -53  98]]
qr factorization of the said array:
q=
 [[-0.21199958 -0.27930103  0.93650794]
 [-0.63599873 -0.68815735 -0.34920635]
 [ 0.74199852 -0.66964945 -0.03174603]] 
r=
 [[-18.86796226 -65.4018692  109.39178122]
 [  0.           6.67798664 -25.24309237]
 [  0.           0.           2.28571429]]


# What next?
More exercises: https://www.w3resource.com/python-exercises/numpy/