# Tools - NumPy

*NumPy is the fundamental library for scientific computing with Python. NumPy is centered around a powerful N-dimensional array object, and it also contains useful linear algebra, Fourier transform, and random number functions.*

- mainly based on numpy tutorial from Aurélien Geron in Hands on machine learning v2: https://github.com/ageron/handson-ml2
- the exercises are available at https://www.w3resource.com/python-exercises/numpy

# Summary

## 1. Creating arrays
## 2. Reshaping an array
## 3. Arithmetic operations
## 4. Broadcasting
## 5. Conditional operators
## 6. Mathematical and statistical functions
## 7. Array indexing
## 8. Iterating
## 9. Stacking arrays
## 10. Splitting arrays
## 11. Linear algebra
## 12. Vectorization
## 13. Saving and loading


---

# 1. Creating arrays

Let's import `numpy`. Most people import it as `np`:

In [ ]:
import numpy as np

## 1.1 `np.zeros`

The `zeros` function creates an array containing any number of zeros:

In [ ]:
np.zeros(5)

It's just as easy to create a 2D array (ie. a matrix) by providing a tuple with the desired number of rows and columns. For example, here's a 3x4 matrix:

In [ ]:
np.zeros((3,4))

## 1.2 Some vocabulary

* In NumPy, each dimension is called an **axis**.
* The number of axes is called the **rank**.
    * For example, the above 3x4 matrix is an array of rank 2 (it is 2-dimensional).
    * The first axis has length 3, the second has length 4.
* An array's list of axis lengths is called the **shape** of the array.
    * For example, the above matrix's shape is `(3, 4)`.
    * The rank is equal to the shape's length.
* The **size** of an array is the total number of elements, which is the product of all axis lengths (eg. 3*4=12)

In [ ]:
a = np.zeros((3,4))
a

In [ ]:
a.shape

In [ ]:
a.ndim  # equal to len(a.shape)

In [ ]:
a.size

## 1.3 N-dimensional arrays
You can also create an N-dimensional array of arbitrary rank. For example, here's a 3D array (rank=3), with shape `(2,3,4)`:

In [ ]:
np.zeros((2,3,4))

## 1.4 `np.ones`
Many other NumPy functions create `ndarrays`.

Here's a 3x4 matrix full of ones:

In [ ]:
np.ones((3,4))

## 1.5 `np.full`
Creates an array of the given shape initialized with the given value. Here's a 3x4 matrix full of `π`.

In [ ]:
np.full((3,4), np.pi)

## 1.6 `np.empty`
An uninitialized 2x3 array (its content is not predictable, as it is whatever is in memory at that point):

In [ ]:
np.empty((2,3))

## 1.7 np.array
Of course you can initialize an `ndarray` using a regular python array. Just call the `array` function:

In [ ]:
np.array([[1,2,3,4], [10, 20, 30, 40]])

## 1.8 `np.arange`
You can create an `ndarray` using NumPy's `range` function, which is similar to python's built-in `range` function:

In [ ]:
np.arange(1, 5)

It also works with floats:

In [ ]:
np.arange(1.0, 5.0)

Of course you can provide a step parameter:

In [ ]:
np.arange(1, 5, 0.5)

However, when dealing with floats, the exact number of elements in the array is not always predictible. For example, consider this:

In [ ]:
print(np.arange(0, 5/3, 1/3)) # depending on floating point errors, the max value is 4/3 or 5/3.
print(np.arange(0, 5/3, 0.333333333))
print(np.arange(0, 5/3, 0.333333334))

## 1.9 `np.linspace`
For this reason, it is generally preferable to use the `linspace` function instead of `arange` when working with floats. The `linspace` function returns an array containing a specific number of points evenly distributed between two values (note that the maximum value is *included*, contrary to `arange`):

In [ ]:
print(np.linspace(0, 5/3, 6))

## 1.10 `np.rand` and `np.randn`
A number of functions are available in NumPy's `random` module to create `ndarray`s initialized with random values.
For example, here is a 3x4 matrix initialized with random floats between 0 and 1 (uniform distribution):

In [ ]:
np.random.rand(3,4)

Here's a 3x4 matrix containing random floats sampled from a univariate [normal distribution](https://en.wikipedia.org/wiki/Normal_distribution) (Gaussian distribution) of mean 0 and variance 1:

In [ ]:
np.random.randn(3,4)

To give you a feel of what these distributions look like, let's use matplotlib (see the [matplotlib tutorial](tools_matplotlib.ipynb) for more details):

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt

In [ ]:
plt.hist(np.random.rand(100000), normed=True, bins=100, histtype="step", color="blue", label="rand")
plt.hist(np.random.randn(100000), normed=True, bins=100, histtype="step", color="red", label="randn")
plt.axis([-2.5, 2.5, 0, 1.1])
plt.legend(loc = "upper left")
plt.title("Random distributions")
plt.xlabel("Value")
plt.ylabel("Density")
plt.show()

## 1.11 np.from function
You can also initialize an `ndarray` using a function:

In [ ]:
def my_function(z, y, x):
    return x * y + z

np.fromfunction(my_function, (3, 2, 10))

NumPy first creates three `ndarrays` (one per dimension), each of shape `(2, 10)`. Each array has values equal to the coordinate along a specific axis. For example, all elements in the `z` array are equal to their z-coordinate:

    [[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
      [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
    
     [[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
      [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]
    
     [[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
      [ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]]]

So the terms x, y and z in the expression `x * y + z` above are in fact `ndarray`s (we will discuss arithmetic operations on arrays below).  The point is that the function `my_function` is only called *once*, instead of once per element. This makes initialization very efficient.

## 1.12 EXERCISES Creating array

<div class="alert alert-success">

<b>EXERCISES</b>:

 <ul>
  <li>Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10</li>
  <li>Write a NumPy program to create a array with values ranging from 12 to 38</li>
  <li>Write a NumPy program to create a 2-dimensional array of size 2 x 3 (composed of 4-byte integer elements), also print the shape, type and data type of the array.</li>
</ul>
</div>

# 2. Reshaping an array
## 2.1 In place
Changing the shape of an `ndarray` is as simple as setting its `shape` attribute. However, the array's size must remain the same.

In [ ]:
g = np.arange(24)
print(g)
print("Rank:", g.ndim)

In [ ]:
g.shape = (6, 4)
print(g)
print("Rank:", g.ndim)

In [ ]:
g.shape = (2, 3, 4)
print(g)
print("Rank:", g.ndim)

## 2.2 `reshape`
The `reshape` function returns a new `ndarray` object pointing at the *same* data. This means that modifying one array will also modify the other.

In [ ]:
g2 = g.reshape(4,6)
print(g2)
print("Rank:", g2.ndim)

Set item at row 1, col 2 to 999 (more about indexing below).

In [ ]:
g2[1, 2] = 999
g2

The corresponding element in `g` has been modified.

In [ ]:
g

## 2.3 `ravel`
Finally, the `ravel` function returns a new one-dimensional `ndarray` that also points to the same data:

In [ ]:
g.ravel()

## 2.4 EXERCISES Reshaping an array

<div class="alert alert-success">

<b>EXERCISE</b>:

Write a NumPy program to change the dimension of an array: 6 rows and 0 columns = (6,) -> 
(3, 3) = 3 rows and 3 columns

</div>

# 3. Arithmetic operations
All the usual arithmetic operators (`+`, `-`, `*`, `/`, `//`, `**`, etc.) can be used with `ndarray`s. They apply *elementwise*:

In [ ]:
a = np.array([14, 23, 32, 41])
b = np.array([5,  4,  3,  2])
print("a + b  =", a + b)
print("a - b  =", a - b)
print("a * b  =", a * b)
print("a / b  =", a / b)
print("a // b  =", a // b)
print("a % b  =", a % b)
print("a ** b =", a ** b)

Note that the multiplication is *not* a matrix multiplication. We will discuss matrix operations below.

The arrays must have the same shape. If they do not, NumPy will apply the *broadcasting rules*.

# 4. Broadcasting

In general, when NumPy expects arrays of the same shape but finds that this is not the case, it applies the so-called *broadcasting* rules:

## 4.1 First rule
*If the arrays do not have the same rank, then a 1 will be prepended to the smaller ranking arrays until their ranks match.*

In [ ]:
h = np.arange(5).reshape(1, 1, 5)
h

Now let's try to add a 1D array of shape `(5,)` to this 3D array of shape `(1,1,5)`. Applying the first rule of broadcasting!

In [ ]:
h + [10, 20, 30, 40, 50]  # same as: h + [[[10, 20, 30, 40, 50]]]

## 4.2 Second rule
*Arrays with a 1 along a particular dimension act as if they had the size of the array with the largest shape along that dimension. The value of the array element is repeated along that dimension.*

In [ ]:
k = np.arange(6).reshape(2, 3)
k

Let's try to add a 2D array of shape `(2,1)` to this 2D `ndarray` of shape `(2, 3)`. NumPy will apply the second rule of broadcasting:

In [ ]:
k + [[100], [200]]  # same as: k + [[100, 100, 100], [200, 200, 200]]

Combining rules 1 & 2, we can do this:

In [ ]:
k + [100, 200, 300]  # after rule 1: [[100, 200, 300]], and after rule 2: [[100, 200, 300], [100, 200, 300]]

And also, very simply:

In [ ]:
k + 1000  # same as: k + [[1000, 1000, 1000], [1000, 1000, 1000]]

## 4.3 Third rule
*After rules 1 & 2, the sizes of all arrays must match.*

In [ ]:
try:
    k + [33, 44]
except ValueError as e:
    print(e)

Broadcasting rules are used in many NumPy operations, not just arithmetic operations, as we will see below.
For more details about broadcasting, check out [the documentation](https://docs.scipy.org/doc/numpy-dev/user/basics.broadcasting.html).

## 4.4 Conclusion
Broadcasting two arrays together follows these rules:

1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

Here are some applications of broadcasting:

In [ ]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:

print(np.reshape(v, (3, 1)) * w)

In [ ]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:

print(x + v)


In [ ]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:

print((x.T + w).T)

In [ ]:
# Another solution is to reshape w to be a row vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

In [ ]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
print(x * 2)


## 4.5 EXERCISES Broadcasting

<div class="alert alert-success">

<b>EXERCISES</b>:

<ul>
  <li>Write a NumPy program to broadcast on different shapes of arrays where p(3,3) + q(3).</li>
  <li>Write a NumPy program to broadcast on different shapes of arrays where a(,3) + b(3).</li>
</ul>


# 5. Conditional operators

The conditional operators also apply elementwise:

In [ ]:
m = np.array([20, -5, 30, 40])
m < [15, 16, 35, 36]

And using broadcasting:

In [ ]:
m < 25  # equivalent to m < [25, 25, 25, 25]

This is most useful in conjunction with boolean indexing (discussed below).

In [ ]:
m[m < 25]

# 6. Mathematical and statistical functions

Many mathematical and statistical functions are available for `ndarray`s.

## 6.1 `ndarray` methods
Some functions are simply `ndarray` methods, for example:

In [ ]:
a = np.array([[-2.5, 3.1, 7], [10, 11, 12]])
print(a)
print("mean =", a.mean())

Note that this computes the mean of all elements in the `ndarray`, regardless of its shape.

Here are a few more useful `ndarray` methods:

In [ ]:
for func in (a.min, a.max, a.sum, a.prod, a.std, a.var):
    print(func.__name__, "=", func())

These functions accept an optional argument `axis` which lets you ask for the operation to be performed on elements along the given axis. For example:

In [ ]:
c=np.arange(24).reshape(2,3,4)
c

In [ ]:
c.sum(axis=0)  # sum across matrices

In [ ]:
c.sum(axis=1)  # sum across rows

You can also sum over multiple axes:

In [ ]:
c.sum(axis=(0,2))  # sum across matrices and columns

In [ ]:
0+1+2+3 + 12+13+14+15, 4+5+6+7 + 16+17+18+19, 8+9+10+11 + 20+21+22+23

## 6.2 Universal functions
NumPy also provides fast elementwise functions called *universal functions*, or **ufunc**. They are vectorized wrappers of simple functions. For example `square` returns a new `ndarray` which is a copy of the original `ndarray` except that each element is squared:

In [ ]:
a = np.array([[-2.5, 3.1, 7], [10, 11, 12]])
np.square(a)

Here are a few more useful unary ufuncs:

In [ ]:
print("Original ndarray")
print(a)
for func in (np.abs, np.sqrt, np.exp, np.log, np.sign, np.ceil, np.modf, np.isnan, np.cos):
    print("\n", func.__name__)
    print(func(a))

## 6.3 Binary ufuncs
There are also many binary ufuncs, that apply elementwise on two `ndarray`s.  Broadcasting rules are applied if the arrays do not have the same shape:

In [ ]:
a = np.array([1, -2, 3, 4])
b = np.array([2, 8, -1, 7])
np.add(a, b)  # equivalent to a + b

In [ ]:
np.greater(a, b)  # equivalent to a > b

In [ ]:
np.maximum(a, b)

## 6.4 EXERCISES Mathematical and statistical functions


<div class="alert alert-success">

<b>EXERCISES</b>:

<ul>
  <li>Write a NumPy program to compute logarithm of the sum of exponentiations of the inputs, sum of exponentiations of the inputs in base-2.</li>
  <li>Write a NumPy program to get true division of the element-wise array inputs.</li>
  <li>Write a NumPy program to multiply a matrix by another matrix of complex numbers and create a new matrix of complex numbers.</li>
  <li>Write a NumPy program to calculate round, floor, ceiling, truncated and round (to the given number of decimals) of the input, element-wise of a given array. </li>
</ul>



# 7. Array indexing
## 7.1 One-dimensional arrays
One-dimensional NumPy arrays can be accessed more or less like regular python arrays:

In [ ]:
a = np.array([1, 5, 3, 19, 13, 7, 3])
a[3]

In [ ]:
a[2:5]

In [ ]:
a[2:-1]

In [ ]:
a[:2]

In [ ]:
a[2::2]

In [ ]:
a[::-1]

Of course, you can modify elements:

In [ ]:
a[3]=999
a

You can also modify an `ndarray` slice:

In [ ]:
a[2:5] = [997, 998, 999]
a

## 7.2 Differences with regular python arrays
Contrary to regular python arrays, if you assign a single value to an `ndarray` slice, it is copied across the whole slice, thanks to broadcasting rules discussed above.

In [ ]:
a[2:5] = -1
a

Also, you cannot grow or shrink `ndarray`s this way:

In [ ]:
try:
    a[2:5] = [1,2,3,4,5,6]  # too long
except ValueError as e:
    print(e)

You cannot delete elements either:

In [ ]:
try:
    del a[2:5]
except ValueError as e:
    print(e)

Last but not least, `ndarray` **slices are actually *views*** on the same data buffer. This means that if you create a slice and modify it, you are actually going to modify the original `ndarray` as well!

In [ ]:
a_slice = a[2:6]
a_slice[1] = 1000
a  # the original array was modified!

In [ ]:
a[3] = 2000
a_slice  # similarly, modifying the original array modifies the slice!

If you want a copy of the data, you need to use the `copy` method:

In [ ]:
another_slice = a[2:6].copy()
another_slice[1] = 3000
a  # the original array is untouched

In [ ]:
a[3] = 4000
another_slice  # similary, modifying the original array does not affect the slice copy

## 7.3 Multi-dimensional arrays
Multi-dimensional arrays can be accessed in a similar way by providing an index or slice for each axis, separated by commas:

In [ ]:
b = np.arange(48).reshape(4, 12)
b

In [ ]:
b[1, 2]  # row 1, col 2

In [ ]:
b[1, :]  # row 1, all columns

In [ ]:
b[:, 1]  # all rows, column 1

**Caution**: note the subtle difference between these two expressions: 

In [ ]:
b[1, :]

In [ ]:
b[1:2, :]

The first expression returns row 1 as a 1D array of shape `(12,)`, while the second returns that same row as a 2D array of shape `(1, 12)`.

## 7.4 Higher dimensions
Everything works just as well with higher dimensional arrays, but it's useful to look at a few examples:

In [ ]:
c = b.reshape(4,2,6)
c

In [ ]:
c[2, 1, 4]  # matrix 2, row 1, col 4

In [ ]:
c[2, :, 3]  # matrix 2, all rows, col 3

If you omit coordinates for some axes, then all elements in these axes are returned:

In [ ]:
c[2, 1]  # Return matrix 2, row 1, all columns.  This is equivalent to c[2, 1, :]

## 7.5 Boolean indexing
You can also provide an `ndarray` of boolean values on one axis to specify the indices that you want to access.

In [ ]:
b = np.arange(48).reshape(4, 12)
b

In [ ]:
rows_on = np.array([True, False, True, False])
b[rows_on, :]  # Rows 0 and 2, all columns. Equivalent to b[(0, 2), :]

In [ ]:
cols_on = np.array([False, True, False] * 4)
b[:, cols_on]  # All rows, columns 1, 4, 7 and 10

## 7.6 `np.ix_`
You cannot use boolean indexing this way on multiple axes, but you can work around this by using the `ix_` function:

In [ ]:
b[np.ix_(rows_on, cols_on)]

In [ ]:
np.ix_(rows_on, cols_on)

If you use a boolean array that has the same shape as the `ndarray`, then you get in return a 1D array containing all the values that have `True` at their coordinate. This is generally used along with conditional operators:

In [ ]:
b[b % 3 == 1]

## 7.7 EXERCISES Array indexing

<div class="alert alert-success">

<b>EXERCISES</b>:

<ul>
  <li>Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort the array on height.</li>
  <li>Write a NumPy program to sort the student id with increasing height of the students from given students id and height. Print the integer indices that describes the sort order by multiple columns and the sorted data.</li>
</ul>


# 8. Iterating
Iterating over `ndarray`s is very similar to iterating over regular python arrays. Note that iterating over multidimensional arrays is done with respect to the first axis.

In [ ]:
c = np.arange(24).reshape(2, 3, 4)  # A 3D array (composed of two 3x4 matrices)
c

In [ ]:
for m in c:
    print("Item:")
    print(m)

In [ ]:
for i in range(len(c)):  # Note that len(c) == c.shape[0]
    print("Item:")
    print(c[i])

If you want to iterate on *all* elements in the `ndarray`, simply iterate over the `flat` attribute:

In [ ]:
for i in c.flat:
    print("Item:", i)

# 9. Stacking arrays
It is often useful to stack together different arrays. NumPy offers several functions to do just that. Let's start by creating a few arrays.

In [ ]:
q1 = np.full((3,4), 1.0)
q1

In [ ]:
q2 = np.full((4,4), 2.0)
q2

In [ ]:
q3 = np.full((3,4), 3.0)
q3

## 9.1 `vstack`
Now let's stack them vertically using `vstack`:

In [ ]:
q4 = np.vstack((q1, q2, q3))
q4

In [ ]:
q4.shape

This was possible because q1, q2 and q3 all have the same shape (except for the vertical axis, but that's ok since we are stacking on that axis).

## 9.2 `hstack`
We can also stack arrays horizontally using `hstack`:

In [ ]:
q5 = np.hstack((q1, q3))
q5

In [ ]:
q5.shape

This is possible because q1 and q3 both have 3 rows. But since q2 has 4 rows, it cannot be stacked horizontally with q1 and q3:

In [ ]:
try:
    q5 = np.hstack((q1, q2, q3))
except ValueError as e:
    print(e)

## `concatenate`
The `concatenate` function stacks arrays along any given existing axis.

In [ ]:
q7 = np.concatenate((q1, q2, q3), axis=0)  # Equivalent to vstack
q7

In [ ]:
q7.shape

As you might guess, `hstack` is equivalent to calling `concatenate` with `axis=1`.

## 9.3 `stack`
The `stack` function stacks arrays along a new axis. All arrays have to have the same shape.

In [ ]:
q8 = np.stack((q1, q3))
q8

In [ ]:
q8.shape

# 10. Splitting arrays
Splitting is the opposite of stacking. For example, let's use the `vsplit` function to split a matrix vertically.

First let's create a 6x4 matrix:

In [ ]:
r = np.arange(24).reshape(6,4)
r

Now let's split it in three equal parts, vertically:

In [ ]:
r1, r2, r3 = np.vsplit(r, 3)
r1

In [ ]:
r2

In [ ]:
r3

There is also a `split` function which splits an array along any given axis. Calling `vsplit` is equivalent to calling `split` with `axis=0`. There is also an `hsplit` function, equivalent to calling `split` with `axis=1`:

In [ ]:
r4, r5 = np.hsplit(r, 2)
r4

In [ ]:
r5

## EXERCISES Splitting arrays

<div class="alert alert-success">

<b>EXERCISES</b>:

<ul>
  <li>Write a NumPy program to split an given array into multiple sub-arrays vertically (row-wise). </li>
  <li>Write a NumPy program to split array into multiple sub-arrays along the 3rd axis.</li>
</ul>

# 11. Linear algebra
NumPy 2D arrays can be used to represent matrices efficiently in python. We will just quickly go through some of the main matrix operations available. For more details about Linear Algebra, vectors and matrics, go through the [Linear Algebra tutorial](math_linear_algebra.ipynb).

## 11.1 Matrix transpose
The `T` attribute is equivalent to calling `transpose()` when the rank is ≥2:

In [ ]:
m1 = np.arange(10).reshape(2,5)
m1

In [ ]:
m1.T

The `T` attribute has no effect on rank 0 (empty) or rank 1 arrays:

In [ ]:
m2 = np.arange(5)
m2

In [ ]:
m2.T

We can get the desired transposition by first reshaping the 1D array to a single-row matrix (2D):

In [ ]:
m2r = m2.reshape(1,5)
m2r

In [ ]:
m2r.T

## 11.2 Matrix dot product
Let's create two matrices and execute a matrix [dot product](https://en.wikipedia.org/wiki/Dot_product) using the `dot` method.

In [ ]:
n1 = np.arange(10).reshape(2, 5)
n1

In [ ]:
n2 = np.arange(15).reshape(5,3)
n2

In [ ]:
n1.dot(n2)

**Caution**: as mentionned previously, `n1*n2` is *not* a dot product, it is an elementwise product.

## 11.3 Matrix inverse and pseudo-inverse
Many of the linear algebra functions are available in the `numpy.linalg` module, in particular the `inv` function to compute a square matrix's inverse:

In [ ]:
import numpy.linalg as linalg

m3 = np.array([[1,2,3],[5,7,11],[21,29,31]])
m3

In [ ]:
linalg.inv(m3)

You can also compute the [pseudoinverse](https://en.wikipedia.org/wiki/Moore%E2%80%93Penrose_pseudoinverse) using `pinv`:

In [ ]:
linalg.pinv(m3)

## 11.4 Identity matrix
The product of a matrix by its inverse returns the identiy matrix (with small floating point errors):

In [ ]:
m3.dot(linalg.inv(m3))

You can create an identity matrix of size NxN by calling `eye`:

In [ ]:
np.eye(3)

## 11.5 QR decomposition
The `qr` function computes the [QR decomposition](https://en.wikipedia.org/wiki/QR_decomposition) of a matrix:

In [ ]:
q, r = linalg.qr(m3)
q

In [ ]:
r

In [ ]:
q.dot(r)  # q.r equals m3

## 11.6 Determinant
The `det` function computes the [matrix determinant](https://en.wikipedia.org/wiki/Determinant):

In [ ]:
linalg.det(m3)  # Computes the matrix determinant

## 11.7 Eigenvalues and eigenvectors
The `eig` function computes the [eigenvalues and eigenvectors](https://en.wikipedia.org/wiki/Eigenvalues_and_eigenvectors) of a square matrix:

In [ ]:
eigenvalues, eigenvectors = linalg.eig(m3)
eigenvalues # λ

In [ ]:
eigenvectors # v

In [ ]:
m3.dot(eigenvectors) - eigenvalues * eigenvectors  # m3.v - λ*v = 0

## 11.8 Singular Value Decomposition
The `svd` function takes a matrix and returns its [singular value decomposition](https://en.wikipedia.org/wiki/Singular_value_decomposition):

In [ ]:
m4 = np.array([[1,0,0,0,2], [0,0,3,0,0], [0,0,0,0,0], [0,2,0,0,0]])
m4

In [ ]:
U, S_diag, V = linalg.svd(m4)
U

In [ ]:
S_diag

The `svd` function just returns the values in the diagonal of Σ, but we want the full Σ matrix, so let's create it:

In [ ]:
S = np.zeros((4, 5))
S[np.diag_indices(4)] = S_diag
S  # Σ

In [ ]:
V

In [ ]:
U.dot(S).dot(V) # U.Σ.V == m4

## 11.9 Diagonal and trace

In [ ]:
np.diag(m3)  # the values in the diagonal of m3 (top left to bottom right)

In [ ]:
np.trace(m3)  # equivalent to np.diag(m3).sum()

## 11.10 Solving a system of linear scalar equations

The `solve` function solves a system of linear scalar equations, such as:

* $2x + 6y = 6$
* $5x + 3y = -9$

In [ ]:
coeffs  = np.array([[2, 6], [5, 3]])
depvars = np.array([6, -9])
solution = linalg.solve(coeffs, depvars)
solution

Let's check the solution:

In [ ]:
coeffs.dot(solution), depvars  # yep, it's the same

Looks good! Another way to check the solution:

In [ ]:
np.allclose(coeffs.dot(solution), depvars)

## EXERCISES Linear Algebra

<div class="alert alert-success">

<b>EXERCISES</b>:

<ul>
  <li>Write a NumPy program to compute the multiplication of two given matrixes. </li>
  <li>Write a NumPy program to compute the outer product of two given vectors.</li>
  <li>Write a NumPy program to compute the eigenvalues and right eigenvectors of a given square array.</li>
  <li>Write a NumPy program to calculate the QR decomposition of a given matrix.</li>
  <li>Write a NumPy program to get the qr factorization of a given array.</li>
</ul>


# 12. Vectorization
Instead of executing operations on individual array items, one at a time, your code is much more efficient if you try to stick to array operations. This is called *vectorization*. This way, you can benefit from NumPy's many optimizations.

For example, let's say we want to generate a 768x1024 array based on the formula $sin(xy/40.5)$. A **bad** option would be to do the math in python using nested loops:

In [ ]:
import math
data = np.empty((768, 1024))
for y in range(768):
    for x in range(1024):
        data[y, x] = math.sin(x*y/40.5)  # BAD! Very inefficient.

Sure, this works, but it's terribly inefficient since the loops are taking place in pure python. Let's vectorize this algorithm. First, we will use NumPy's `meshgrid` function which generates coordinate matrices from coordinate vectors.

In [ ]:
x_coords = np.arange(0, 1024)  # [0, 1, 2, ..., 1023]
y_coords = np.arange(0, 768)   # [0, 1, 2, ..., 767]
X, Y = np.meshgrid(x_coords, y_coords)
X

In [ ]:
Y

As you can see, both `X` and `Y` are 768x1024 arrays, and all values in `X` correspond to the horizontal coordinate, while all values in `Y` correspond to the the vertical coordinate.

Now we can simply compute the result using array operations:

In [ ]:
data = np.sin(X*Y/40.5)

Now we can plot this data using matplotlib's `imshow` function (see the [matplotlib tutorial](tools_matplotlib.ipynb)).

In [ ]:
import matplotlib.pyplot as plt
import matplotlib.cm as cm
fig = plt.figure(1, figsize=(7, 6))
plt.imshow(data, cmap=cm.hot, interpolation="bicubic")
plt.show()

# 13. Saving and loading
NumPy makes it easy to save and load `ndarray`s in binary or text format.

## 13.1 Binary `.npy` format
Let's create a random array and save it.

In [ ]:
a = np.random.rand(2,3)
a

In [ ]:
np.save("my_array", a)

Done! Since the file name contains no file extension was provided, NumPy automatically added `.npy`. Let's take a peek at the file content:

In [ ]:
with open("my_array.npy", "rb") as f:
    content = f.read()

content

To load this file into a NumPy array, simply call `load`:

In [ ]:
a_loaded = np.load("my_array.npy")
a_loaded

## 13.2 Text format
Let's try saving the array in text format:

In [ ]:
np.savetxt("my_array.csv", a)

Now let's look at the file content:

In [ ]:
with open("my_array.csv", "rt") as f:
    print(f.read())

This is a CSV file with tabs as delimiters. You can set a different delimiter:

In [ ]:
np.savetxt("my_array.csv", a, delimiter=",")

To load this file, just use `loadtxt`:

In [ ]:
a_loaded = np.loadtxt("my_array.csv", delimiter=",")
a_loaded

## 13.3 Zipped `.npz` format
It is also possible to save multiple arrays in one zipped file:

In [ ]:
b = np.arange(24, dtype=np.uint8).reshape(2, 3, 4)
b

In [ ]:
np.savez("my_arrays", my_a=a, my_b=b)

Again, let's take a peek at the file content. Note that the `.npz` file extension was automatically added.

In [ ]:
with open("my_arrays.npz", "rb") as f:
    content = f.read()

repr(content)[:180] + "[...]"

You then load this file like so:

In [ ]:
my_arrays = np.load("my_arrays.npz")
my_arrays

This is a dict-like object which loads the arrays lazily:

In [ ]:
my_arrays.keys()

In [ ]:
my_arrays["my_a"]

## Further reading

Now you know all the fundamentals of NumPy, but there are many more options available. 
The best way to learn more is to experiment with NumPy, and go through the excellent [reference documentation](http://docs.scipy.org/doc/numpy/reference/index.html) to find more functions and features you may be interested in.

Tutorials (many good online tutorials!):
* https://docs.scipy.org/doc/numpy/user/quickstart.html
* https://www.machinelearningplus.com/python/numpy-tutorial-part1-array-python-examples/
* https://www.guru99.com/numpy-tutorial.html